// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClG9JrD4uLLjh17l-7y4w2hO6b8GsxIzw',
    appId: '1:864009712887:web:3cfa11ae391b09807d4ff2',
    messagingSenderId: '864009712887',
    projectId: 'my-project-81be5',
    authDomain: 'my-project-81be5.firebaseapp.com',
    storageBucket: 'my-project-81be5.firebasestorage.app',
    measurementId: 'G-M7GKF8FXRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdSAq3dQ2wddPaEBlDilXZtEt7JNpmq7M',
    appId: '1:864009712887:android:2fcf6ae4a5ecb38f7d4ff2',
    messagingSenderId: '864009712887',
    projectId: 'my-project-81be5',
    storageBucket: 'my-project-81be5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtapOyvcG9QlN7ut8dCD2gWPyefhKNnTo',
    appId: '1:864009712887:ios:1bb8338713a3963b7d4ff2',
    messagingSenderId: '864009712887',
    projectId: 'my-project-81be5',
    storageBucket: 'my-project-81be5.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtapOyvcG9QlN7ut8dCD2gWPyefhKNnTo',
    appId: '1:864009712887:ios:1bb8338713a3963b7d4ff2',
    messagingSenderId: '864009712887',
    projectId: 'my-project-81be5',
    storageBucket: 'my-project-81be5.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClG9JrD4uLLjh17l-7y4w2hO6b8GsxIzw',
    appId: '1:864009712887:web:60150dfa12712f847d4ff2',
    messagingSenderId: '864009712887',
    projectId: 'my-project-81be5',
    authDomain: 'my-project-81be5.firebaseapp.com',
    storageBucket: 'my-project-81be5.firebasestorage.app',
    measurementId: 'G-L38RKNW1XC',
  );
}
